# Generated by Django 3.2.7 on 2021-10-05 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 5, 19, 21, 9, 16092, tzinfo=utc), verbose_name='orderedTime'),
        ),
    ]
