# Generated by Django 3.2.7 on 2021-10-05 19:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_orders_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 5, 19, 54, 12, 975833, tzinfo=utc), verbose_name='orderedTime'),
        ),
    ]
