# Generated by Django 3.2.7 on 2021-10-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20211001_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='time_when_employee_left',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_time',
        ),
    ]
