# Generated by Django 3.2.7 on 2021-10-01 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20211001_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='desert_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.desert'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='drink_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.drink'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='pizza_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.pizza'),
        ),
    ]
