# Generated by Django 3.0.5 on 2021-10-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_employee_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='status',
            new_name='status_employee',
        ),
    ]
