# Generated by Django 3.2.7 on 2021-10-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_orders_order_time'),
        ('restaurant', '0008_auto_20211005_1522'),
    ]

    operations = [
    ]
