# Generated by Django 3.2.7 on 2021-10-06 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_merge_20211006_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 6, 18, 56, 13, 615773, tzinfo=utc), verbose_name='orderedTime'),
        ),
    ]
