# Generated by Django 3.2.7 on 2021-10-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_rename_status_employee_status_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='time_when_employee_left',
        ),
    ]
