# Generated by Django 3.0.5 on 2021-10-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20211004_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='time_when_employee_left',
            field=models.DateTimeField(auto_now_add=True, verbose_name='orderedTime'),
        ),
    ]
