# Generated by Django 3.0.5 on 2021-10-04 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20211004_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='time_when_employee_left',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 4, 18, 55, 53, 987579), verbose_name='orderedTime'),
        ),
    ]
