# Generated by Django 3.0.5 on 2021-10-04 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_auto_20211004_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='time_when_employee_left',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 4, 17, 20, 51, 652091, tzinfo=utc), verbose_name='orderedTime'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 4, 17, 20, 51, 704005, tzinfo=utc), verbose_name='orderedTime'),
        ),
    ]
