# Generated by Django 3.0.5 on 2021-09-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(default=0)),
                ('order_time', models.DateTimeField(verbose_name='orderedTime')),
                ('order_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('pizza_id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Orders')),
                ('pizza_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Pizza')),
            ],
        ),
    ]
