# Generated by Django 3.2.7 on 2021-09-21 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('postal_code', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('house_number', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(default=0)),
                ('discount_available', models.BooleanField(default=False)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.address')),
            ],
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=200)),
                ('time_when_deliverer_left', models.DateTimeField(verbose_name='orderedTime')),
            ],
        ),
        migrations.CreateModel(
            name='desert',
            fields=[
                ('desert_id', models.AutoField(primary_key=True, serialize=False)),
                ('desert_name', models.CharField(max_length=200)),
                ('desert_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='drink',
            fields=[
                ('drink_id', models.AutoField(primary_key=True, serialize=False)),
                ('drink_name', models.CharField(max_length=200)),
                ('drink_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('area_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='menu_item',
            fields=[
                ('menu_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('desert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.desert')),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.drink')),
                ('pizza_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='order_line',
            fields=[
                ('order_line_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('menu_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu_item')),
            ],
        ),
        migrations.CreateModel(
            name='pizza_toppings',
            fields=[
                ('pizza_toppings_id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='topping',
            fields=[
                ('topping_id', models.AutoField(primary_key=True, serialize=False)),
                ('topping_name', models.CharField(max_length=200)),
                ('topping_price', models.FloatField()),
                ('vegeterian', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='total_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Order_Pizza',
        ),
        migrations.AddField(
            model_name='pizza_toppings',
            name='topping_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.topping'),
        ),
        migrations.AddField(
            model_name='order_line',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.orders'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.employee'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.customer'),
        ),
    ]
