# Generated by Django 3.2.7 on 2021-09-17 17:26

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210917_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='id',
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_id',
            field=models.AutoField(default=builtins.any, editable=False, primary_key=True, serialize=False),
        ),
    ]
