# Generated by Django 3.2.7 on 2021-09-17 17:27

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210917_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_id',
            field=models.AutoField(default=builtins.any, primary_key=True, serialize=False),
        ),
    ]
