# Generated by Django 3.2.7 on 2021-09-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_pizza_pizza_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
