# Generated by Django 3.2.7 on 2021-09-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_pizza_pizza_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_Pizza',
        ),
    ]
